export const WALLETCONNECT_PROJECT_ID_WALLET =
  process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID_WALLET

export const WALLETCONNECT_PROJECT_ID_DAPP =
  process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID_DAPP
